defaults: &defaults
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  database: flywheel_development

development: &development
  <<: *defaults

test: &test
  <<: *defaults
  database: flywheel_test

production:
  <<: *defaults
  database: flywheel_development